In [1]:
string="7+55*x^22"
string_mono=string.split("+")
string_mono

['7', '55*x^22']

In [2]:
int(string_mono[1][5:])

22

In [15]:
string2="22*x^44"
string2_power=string2.split("^")
string2_power
for x in string2_power:
    print(x.split("*"))

['22', 'x']
['44']


In [10]:
string2_power

['22*x']

In [1]:
from polynomial import Polynomial
a=Polynomial.from_string("-1+6*x-7*x^4+3*x^2")

-1+6*x-7*x^4+3*x^2
[-1  6  3  0 -7]


In [2]:
print(a)

[-1  6  3  0 -7]


In [5]:
import numpy as np
a = np.zeros(7,dtype = int)
b = [2,5,7,9,3]
a[2:] = b
print(a)

[0 0 2 5 7 9 3]


In [ ]:
py

In [1]:
from polynomial import Polynomial

a = Polynomial.from_string("-4 + x^2")
b = Polynomial.from_string("x^2 - 4")
print( a - b )

0


In [2]:
print( a - b )

In [5]:
for i,j in zip(a, b):
    print(i,j)
    if i != j:
        print("nope")
print('yes')

TypeError: 'Polynomial' object is not iterable

In [3]:
c = a==b
c.all()

True

In [3]:
from polynomial import Polynomial
a = Polynomial.from_string("-2 - x")
b = Polynomial.from_string("1 + 7*x^2")
c = Polynomial.from_string("-3 -x -7*x^2")
a-b

False

In [9]:
import numpy as np
aa = np.array([-2 -1])
bb = np.array([1, 0, 7])
cc = bb.copy()
cc[:len(aa)] = aa - cc[:len(aa)]
print(cc)

[-4  0  7]


In [1]:
from polynomial import Polynomial
a = Polynomial.from_string("4")
b = Polynomial.from_string("2 - x + 3*x^2")
c = Polynomial.from_string("8 - 4*x + 12*x^2")
a*b

8+8*x+8*x^2

In [4]:
import numpy as np
np.array([4]) * np.array([2, -1, 3])

array([ 8, -4, 12])

In [12]:
first_length = np.array([4, 7]).size
secon_length = np.array([2, -1, 3]).size
coef = np.zeros(first_length+secon_length-1, dtype=int)
idx = 0
for x in np.array([4, 7]):
    if x != 0:
        multip = x * np.array([2, -1, 3])
        print(multip)
        idy = 0
        for y in range(secon_length):
            coef[idy + idx] += multip[idy]
            print(coef)
            idy += 1
    idx += 1
coef

[ 8 -4 12]
[8 0 0 0]
[ 8 -4  0  0]
[ 8 -4 12  0]
[14 -7 21]
[ 8 10 12  0]
[ 8 10  5  0]
[ 8 10  5 21]


array([ 8, 10,  5, 21])